/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxiToPeyiaRouteImport } from './routes/taxi-to-peyia'
import { Route as TaxiToLimassolRouteImport } from './routes/taxi-to-limassol'
import { Route as TaxiToCoralBayRouteImport } from './routes/taxi-to-coral-bay'
import { Route as TaxiToChlorakaRouteImport } from './routes/taxi-to-chloraka'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PaphosAirportTransfersRouteImport } from './routes/paphos-airport-transfers'
import { Route as LarnacaAirportTransfersRouteImport } from './routes/larnaca-airport-transfers'
import { Route as LarnacaAirportToPaphosRouteImport } from './routes/larnaca-airport-to-paphos'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ElRouteImport } from './routes/el'
import { Route as CyprusAirportTransfersRouteImport } from './routes/cyprus-airport-transfers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElIndexRouteImport } from './routes/el.index'
import { Route as ElFaqRouteImport } from './routes/el.faq'
import { Route as ElContactRouteImport } from './routes/el.contact'
import { Route as BlogTopHotelsVillasCoralBayPeyiaRouteImport } from './routes/blog_.top-hotels-villas-coral-bay-peyia'
import { Route as BlogThingsToDoInPaphosRouteImport } from './routes/blog_.things-to-do-in-paphos'
import { Route as BlogLarnacaAirportToPaphosTravelGuideRouteImport } from './routes/blog_.larnaca-airport-to-paphos-travel-guide'
import { Route as BlogHiddenGemsChlorakaKissonergaRouteImport } from './routes/blog_.hidden-gems-chloraka-kissonerga'
import { Route as BlogCyprusTravelTipsFirstTimeVisitorsRouteImport } from './routes/blog_.cyprus-travel-tips-first-time-visitors'
import { Route as BlogCompleteCyprusAirportTransferGuideRouteImport } from './routes/blog_.complete-cyprus-airport-transfer-guide'
import { Route as BlogBestBeachesPaphosCoralBayRouteImport } from './routes/blog_.best-beaches-paphos-coral-bay'

const TaxiToPeyiaRoute = TaxiToPeyiaRouteImport.update({
  id: '/taxi-to-peyia',
  path: '/taxi-to-peyia',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiToLimassolRoute = TaxiToLimassolRouteImport.update({
  id: '/taxi-to-limassol',
  path: '/taxi-to-limassol',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiToCoralBayRoute = TaxiToCoralBayRouteImport.update({
  id: '/taxi-to-coral-bay',
  path: '/taxi-to-coral-bay',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiToChlorakaRoute = TaxiToChlorakaRouteImport.update({
  id: '/taxi-to-chloraka',
  path: '/taxi-to-chloraka',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PaphosAirportTransfersRoute = PaphosAirportTransfersRouteImport.update({
  id: '/paphos-airport-transfers',
  path: '/paphos-airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const LarnacaAirportTransfersRoute = LarnacaAirportTransfersRouteImport.update({
  id: '/larnaca-airport-transfers',
  path: '/larnaca-airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const LarnacaAirportToPaphosRoute = LarnacaAirportToPaphosRouteImport.update({
  id: '/larnaca-airport-to-paphos',
  path: '/larnaca-airport-to-paphos',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ElRoute = ElRouteImport.update({
  id: '/el',
  path: '/el',
  getParentRoute: () => rootRouteImport,
} as any)
const CyprusAirportTransfersRoute = CyprusAirportTransfersRouteImport.update({
  id: '/cyprus-airport-transfers',
  path: '/cyprus-airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElIndexRoute = ElIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElRoute,
} as any)
const ElFaqRoute = ElFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ElRoute,
} as any)
const ElContactRoute = ElContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ElRoute,
} as any)
const BlogTopHotelsVillasCoralBayPeyiaRoute =
  BlogTopHotelsVillasCoralBayPeyiaRouteImport.update({
    id: '/blog_/top-hotels-villas-coral-bay-peyia',
    path: '/blog/top-hotels-villas-coral-bay-peyia',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogThingsToDoInPaphosRoute = BlogThingsToDoInPaphosRouteImport.update({
  id: '/blog_/things-to-do-in-paphos',
  path: '/blog/things-to-do-in-paphos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLarnacaAirportToPaphosTravelGuideRoute =
  BlogLarnacaAirportToPaphosTravelGuideRouteImport.update({
    id: '/blog_/larnaca-airport-to-paphos-travel-guide',
    path: '/blog/larnaca-airport-to-paphos-travel-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHiddenGemsChlorakaKissonergaRoute =
  BlogHiddenGemsChlorakaKissonergaRouteImport.update({
    id: '/blog_/hidden-gems-chloraka-kissonerga',
    path: '/blog/hidden-gems-chloraka-kissonerga',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCyprusTravelTipsFirstTimeVisitorsRoute =
  BlogCyprusTravelTipsFirstTimeVisitorsRouteImport.update({
    id: '/blog_/cyprus-travel-tips-first-time-visitors',
    path: '/blog/cyprus-travel-tips-first-time-visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCompleteCyprusAirportTransferGuideRoute =
  BlogCompleteCyprusAirportTransferGuideRouteImport.update({
    id: '/blog_/complete-cyprus-airport-transfer-guide',
    path: '/blog/complete-cyprus-airport-transfer-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestBeachesPaphosCoralBayRoute =
  BlogBestBeachesPaphosCoralBayRouteImport.update({
    id: '/blog_/best-beaches-paphos-coral-bay',
    path: '/blog/best-beaches-paphos-coral-bay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cyprus-airport-transfers': typeof CyprusAirportTransfersRoute
  '/el': typeof ElRouteWithChildren
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/larnaca-airport-to-paphos': typeof LarnacaAirportToPaphosRoute
  '/larnaca-airport-transfers': typeof LarnacaAirportTransfersRoute
  '/paphos-airport-transfers': typeof PaphosAirportTransfersRoute
  '/reviews': typeof ReviewsRoute
  '/taxi-to-chloraka': typeof TaxiToChlorakaRoute
  '/taxi-to-coral-bay': typeof TaxiToCoralBayRoute
  '/taxi-to-limassol': typeof TaxiToLimassolRoute
  '/taxi-to-peyia': typeof TaxiToPeyiaRoute
  '/blog/best-beaches-paphos-coral-bay': typeof BlogBestBeachesPaphosCoralBayRoute
  '/blog/complete-cyprus-airport-transfer-guide': typeof BlogCompleteCyprusAirportTransferGuideRoute
  '/blog/cyprus-travel-tips-first-time-visitors': typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  '/blog/hidden-gems-chloraka-kissonerga': typeof BlogHiddenGemsChlorakaKissonergaRoute
  '/blog/larnaca-airport-to-paphos-travel-guide': typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  '/blog/things-to-do-in-paphos': typeof BlogThingsToDoInPaphosRoute
  '/blog/top-hotels-villas-coral-bay-peyia': typeof BlogTopHotelsVillasCoralBayPeyiaRoute
  '/el/contact': typeof ElContactRoute
  '/el/faq': typeof ElFaqRoute
  '/el/': typeof ElIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cyprus-airport-transfers': typeof CyprusAirportTransfersRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/larnaca-airport-to-paphos': typeof LarnacaAirportToPaphosRoute
  '/larnaca-airport-transfers': typeof LarnacaAirportTransfersRoute
  '/paphos-airport-transfers': typeof PaphosAirportTransfersRoute
  '/reviews': typeof ReviewsRoute
  '/taxi-to-chloraka': typeof TaxiToChlorakaRoute
  '/taxi-to-coral-bay': typeof TaxiToCoralBayRoute
  '/taxi-to-limassol': typeof TaxiToLimassolRoute
  '/taxi-to-peyia': typeof TaxiToPeyiaRoute
  '/blog/best-beaches-paphos-coral-bay': typeof BlogBestBeachesPaphosCoralBayRoute
  '/blog/complete-cyprus-airport-transfer-guide': typeof BlogCompleteCyprusAirportTransferGuideRoute
  '/blog/cyprus-travel-tips-first-time-visitors': typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  '/blog/hidden-gems-chloraka-kissonerga': typeof BlogHiddenGemsChlorakaKissonergaRoute
  '/blog/larnaca-airport-to-paphos-travel-guide': typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  '/blog/things-to-do-in-paphos': typeof BlogThingsToDoInPaphosRoute
  '/blog/top-hotels-villas-coral-bay-peyia': typeof BlogTopHotelsVillasCoralBayPeyiaRoute
  '/el/contact': typeof ElContactRoute
  '/el/faq': typeof ElFaqRoute
  '/el': typeof ElIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cyprus-airport-transfers': typeof CyprusAirportTransfersRoute
  '/el': typeof ElRouteWithChildren
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/larnaca-airport-to-paphos': typeof LarnacaAirportToPaphosRoute
  '/larnaca-airport-transfers': typeof LarnacaAirportTransfersRoute
  '/paphos-airport-transfers': typeof PaphosAirportTransfersRoute
  '/reviews': typeof ReviewsRoute
  '/taxi-to-chloraka': typeof TaxiToChlorakaRoute
  '/taxi-to-coral-bay': typeof TaxiToCoralBayRoute
  '/taxi-to-limassol': typeof TaxiToLimassolRoute
  '/taxi-to-peyia': typeof TaxiToPeyiaRoute
  '/blog_/best-beaches-paphos-coral-bay': typeof BlogBestBeachesPaphosCoralBayRoute
  '/blog_/complete-cyprus-airport-transfer-guide': typeof BlogCompleteCyprusAirportTransferGuideRoute
  '/blog_/cyprus-travel-tips-first-time-visitors': typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  '/blog_/hidden-gems-chloraka-kissonerga': typeof BlogHiddenGemsChlorakaKissonergaRoute
  '/blog_/larnaca-airport-to-paphos-travel-guide': typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  '/blog_/things-to-do-in-paphos': typeof BlogThingsToDoInPaphosRoute
  '/blog_/top-hotels-villas-coral-bay-peyia': typeof BlogTopHotelsVillasCoralBayPeyiaRoute
  '/el/contact': typeof ElContactRoute
  '/el/faq': typeof ElFaqRoute
  '/el/': typeof ElIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cyprus-airport-transfers'
    | '/el'
    | '/faq'
    | '/fleet'
    | '/larnaca-airport-to-paphos'
    | '/larnaca-airport-transfers'
    | '/paphos-airport-transfers'
    | '/reviews'
    | '/taxi-to-chloraka'
    | '/taxi-to-coral-bay'
    | '/taxi-to-limassol'
    | '/taxi-to-peyia'
    | '/blog/best-beaches-paphos-coral-bay'
    | '/blog/complete-cyprus-airport-transfer-guide'
    | '/blog/cyprus-travel-tips-first-time-visitors'
    | '/blog/hidden-gems-chloraka-kissonerga'
    | '/blog/larnaca-airport-to-paphos-travel-guide'
    | '/blog/things-to-do-in-paphos'
    | '/blog/top-hotels-villas-coral-bay-peyia'
    | '/el/contact'
    | '/el/faq'
    | '/el/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cyprus-airport-transfers'
    | '/faq'
    | '/fleet'
    | '/larnaca-airport-to-paphos'
    | '/larnaca-airport-transfers'
    | '/paphos-airport-transfers'
    | '/reviews'
    | '/taxi-to-chloraka'
    | '/taxi-to-coral-bay'
    | '/taxi-to-limassol'
    | '/taxi-to-peyia'
    | '/blog/best-beaches-paphos-coral-bay'
    | '/blog/complete-cyprus-airport-transfer-guide'
    | '/blog/cyprus-travel-tips-first-time-visitors'
    | '/blog/hidden-gems-chloraka-kissonerga'
    | '/blog/larnaca-airport-to-paphos-travel-guide'
    | '/blog/things-to-do-in-paphos'
    | '/blog/top-hotels-villas-coral-bay-peyia'
    | '/el/contact'
    | '/el/faq'
    | '/el'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cyprus-airport-transfers'
    | '/el'
    | '/faq'
    | '/fleet'
    | '/larnaca-airport-to-paphos'
    | '/larnaca-airport-transfers'
    | '/paphos-airport-transfers'
    | '/reviews'
    | '/taxi-to-chloraka'
    | '/taxi-to-coral-bay'
    | '/taxi-to-limassol'
    | '/taxi-to-peyia'
    | '/blog_/best-beaches-paphos-coral-bay'
    | '/blog_/complete-cyprus-airport-transfer-guide'
    | '/blog_/cyprus-travel-tips-first-time-visitors'
    | '/blog_/hidden-gems-chloraka-kissonerga'
    | '/blog_/larnaca-airport-to-paphos-travel-guide'
    | '/blog_/things-to-do-in-paphos'
    | '/blog_/top-hotels-villas-coral-bay-peyia'
    | '/el/contact'
    | '/el/faq'
    | '/el/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CyprusAirportTransfersRoute: typeof CyprusAirportTransfersRoute
  ElRoute: typeof ElRouteWithChildren
  FaqRoute: typeof FaqRoute
  FleetRoute: typeof FleetRoute
  LarnacaAirportToPaphosRoute: typeof LarnacaAirportToPaphosRoute
  LarnacaAirportTransfersRoute: typeof LarnacaAirportTransfersRoute
  PaphosAirportTransfersRoute: typeof PaphosAirportTransfersRoute
  ReviewsRoute: typeof ReviewsRoute
  TaxiToChlorakaRoute: typeof TaxiToChlorakaRoute
  TaxiToCoralBayRoute: typeof TaxiToCoralBayRoute
  TaxiToLimassolRoute: typeof TaxiToLimassolRoute
  TaxiToPeyiaRoute: typeof TaxiToPeyiaRoute
  BlogBestBeachesPaphosCoralBayRoute: typeof BlogBestBeachesPaphosCoralBayRoute
  BlogCompleteCyprusAirportTransferGuideRoute: typeof BlogCompleteCyprusAirportTransferGuideRoute
  BlogCyprusTravelTipsFirstTimeVisitorsRoute: typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  BlogHiddenGemsChlorakaKissonergaRoute: typeof BlogHiddenGemsChlorakaKissonergaRoute
  BlogLarnacaAirportToPaphosTravelGuideRoute: typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  BlogThingsToDoInPaphosRoute: typeof BlogThingsToDoInPaphosRoute
  BlogTopHotelsVillasCoralBayPeyiaRoute: typeof BlogTopHotelsVillasCoralBayPeyiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taxi-to-peyia': {
      id: '/taxi-to-peyia'
      path: '/taxi-to-peyia'
      fullPath: '/taxi-to-peyia'
      preLoaderRoute: typeof TaxiToPeyiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-to-limassol': {
      id: '/taxi-to-limassol'
      path: '/taxi-to-limassol'
      fullPath: '/taxi-to-limassol'
      preLoaderRoute: typeof TaxiToLimassolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-to-coral-bay': {
      id: '/taxi-to-coral-bay'
      path: '/taxi-to-coral-bay'
      fullPath: '/taxi-to-coral-bay'
      preLoaderRoute: typeof TaxiToCoralBayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-to-chloraka': {
      id: '/taxi-to-chloraka'
      path: '/taxi-to-chloraka'
      fullPath: '/taxi-to-chloraka'
      preLoaderRoute: typeof TaxiToChlorakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paphos-airport-transfers': {
      id: '/paphos-airport-transfers'
      path: '/paphos-airport-transfers'
      fullPath: '/paphos-airport-transfers'
      preLoaderRoute: typeof PaphosAirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/larnaca-airport-transfers': {
      id: '/larnaca-airport-transfers'
      path: '/larnaca-airport-transfers'
      fullPath: '/larnaca-airport-transfers'
      preLoaderRoute: typeof LarnacaAirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/larnaca-airport-to-paphos': {
      id: '/larnaca-airport-to-paphos'
      path: '/larnaca-airport-to-paphos'
      fullPath: '/larnaca-airport-to-paphos'
      preLoaderRoute: typeof LarnacaAirportToPaphosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el': {
      id: '/el'
      path: '/el'
      fullPath: '/el'
      preLoaderRoute: typeof ElRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyprus-airport-transfers': {
      id: '/cyprus-airport-transfers'
      path: '/cyprus-airport-transfers'
      fullPath: '/cyprus-airport-transfers'
      preLoaderRoute: typeof CyprusAirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/': {
      id: '/el/'
      path: '/'
      fullPath: '/el/'
      preLoaderRoute: typeof ElIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/faq': {
      id: '/el/faq'
      path: '/faq'
      fullPath: '/el/faq'
      preLoaderRoute: typeof ElFaqRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/contact': {
      id: '/el/contact'
      path: '/contact'
      fullPath: '/el/contact'
      preLoaderRoute: typeof ElContactRouteImport
      parentRoute: typeof ElRoute
    }
    '/blog_/top-hotels-villas-coral-bay-peyia': {
      id: '/blog_/top-hotels-villas-coral-bay-peyia'
      path: '/blog/top-hotels-villas-coral-bay-peyia'
      fullPath: '/blog/top-hotels-villas-coral-bay-peyia'
      preLoaderRoute: typeof BlogTopHotelsVillasCoralBayPeyiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/things-to-do-in-paphos': {
      id: '/blog_/things-to-do-in-paphos'
      path: '/blog/things-to-do-in-paphos'
      fullPath: '/blog/things-to-do-in-paphos'
      preLoaderRoute: typeof BlogThingsToDoInPaphosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/larnaca-airport-to-paphos-travel-guide': {
      id: '/blog_/larnaca-airport-to-paphos-travel-guide'
      path: '/blog/larnaca-airport-to-paphos-travel-guide'
      fullPath: '/blog/larnaca-airport-to-paphos-travel-guide'
      preLoaderRoute: typeof BlogLarnacaAirportToPaphosTravelGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/hidden-gems-chloraka-kissonerga': {
      id: '/blog_/hidden-gems-chloraka-kissonerga'
      path: '/blog/hidden-gems-chloraka-kissonerga'
      fullPath: '/blog/hidden-gems-chloraka-kissonerga'
      preLoaderRoute: typeof BlogHiddenGemsChlorakaKissonergaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/cyprus-travel-tips-first-time-visitors': {
      id: '/blog_/cyprus-travel-tips-first-time-visitors'
      path: '/blog/cyprus-travel-tips-first-time-visitors'
      fullPath: '/blog/cyprus-travel-tips-first-time-visitors'
      preLoaderRoute: typeof BlogCyprusTravelTipsFirstTimeVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/complete-cyprus-airport-transfer-guide': {
      id: '/blog_/complete-cyprus-airport-transfer-guide'
      path: '/blog/complete-cyprus-airport-transfer-guide'
      fullPath: '/blog/complete-cyprus-airport-transfer-guide'
      preLoaderRoute: typeof BlogCompleteCyprusAirportTransferGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/best-beaches-paphos-coral-bay': {
      id: '/blog_/best-beaches-paphos-coral-bay'
      path: '/blog/best-beaches-paphos-coral-bay'
      fullPath: '/blog/best-beaches-paphos-coral-bay'
      preLoaderRoute: typeof BlogBestBeachesPaphosCoralBayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElRouteChildren {
  ElContactRoute: typeof ElContactRoute
  ElFaqRoute: typeof ElFaqRoute
  ElIndexRoute: typeof ElIndexRoute
}

const ElRouteChildren: ElRouteChildren = {
  ElContactRoute: ElContactRoute,
  ElFaqRoute: ElFaqRoute,
  ElIndexRoute: ElIndexRoute,
}

const ElRouteWithChildren = ElRoute._addFileChildren(ElRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CyprusAirportTransfersRoute: CyprusAirportTransfersRoute,
  ElRoute: ElRouteWithChildren,
  FaqRoute: FaqRoute,
  FleetRoute: FleetRoute,
  LarnacaAirportToPaphosRoute: LarnacaAirportToPaphosRoute,
  LarnacaAirportTransfersRoute: LarnacaAirportTransfersRoute,
  PaphosAirportTransfersRoute: PaphosAirportTransfersRoute,
  ReviewsRoute: ReviewsRoute,
  TaxiToChlorakaRoute: TaxiToChlorakaRoute,
  TaxiToCoralBayRoute: TaxiToCoralBayRoute,
  TaxiToLimassolRoute: TaxiToLimassolRoute,
  TaxiToPeyiaRoute: TaxiToPeyiaRoute,
  BlogBestBeachesPaphosCoralBayRoute: BlogBestBeachesPaphosCoralBayRoute,
  BlogCompleteCyprusAirportTransferGuideRoute:
    BlogCompleteCyprusAirportTransferGuideRoute,
  BlogCyprusTravelTipsFirstTimeVisitorsRoute:
    BlogCyprusTravelTipsFirstTimeVisitorsRoute,
  BlogHiddenGemsChlorakaKissonergaRoute: BlogHiddenGemsChlorakaKissonergaRoute,
  BlogLarnacaAirportToPaphosTravelGuideRoute:
    BlogLarnacaAirportToPaphosTravelGuideRoute,
  BlogThingsToDoInPaphosRoute: BlogThingsToDoInPaphosRoute,
  BlogTopHotelsVillasCoralBayPeyiaRoute: BlogTopHotelsVillasCoralBayPeyiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
