/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZooInPaphosRouteImport } from './routes/zoo-in-paphos'
import { Route as TaxiToPeyiaRouteImport } from './routes/taxi-to-peyia'
import { Route as TaxiToLimassolRouteImport } from './routes/taxi-to-limassol'
import { Route as TaxiToCoralBayRouteImport } from './routes/taxi-to-coral-bay'
import { Route as TaxiToChlorakaRouteImport } from './routes/taxi-to-chloraka'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RuRouteImport } from './routes/ru'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaphosAirportTransfersRouteImport } from './routes/paphos-airport-transfers'
import { Route as MercedesW213VipRouteImport } from './routes/mercedes-w213-vip'
import { Route as LarnacaAirportTransfersRouteImport } from './routes/larnaca-airport-transfers'
import { Route as LarnacaAirportToProtarasRouteImport } from './routes/larnaca-airport-to-protaras'
import { Route as LarnacaAirportToPaphosRouteImport } from './routes/larnaca-airport-to-paphos'
import { Route as LarnacaAirportToAyiaNapaRouteImport } from './routes/larnaca-airport-to-ayia-napa'
import { Route as IndexDotphpRouteImport } from './routes/index[.]php'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ElRouteImport } from './routes/el'
import { Route as CyprusAirportTransfersRouteImport } from './routes/cyprus-airport-transfers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuIndexRouteImport } from './routes/ru.index'
import { Route as ElIndexRouteImport } from './routes/el.index'
import { Route as RuTaxiToPeyiaRouteImport } from './routes/ru.taxi-to-peyia'
import { Route as RuTaxiToLimassolRouteImport } from './routes/ru.taxi-to-limassol'
import { Route as RuTaxiToCoralBayRouteImport } from './routes/ru.taxi-to-coral-bay'
import { Route as RuTaxiToChlorakaRouteImport } from './routes/ru.taxi-to-chloraka'
import { Route as RuReviewsRouteImport } from './routes/ru.reviews'
import { Route as RuPricingRouteImport } from './routes/ru.pricing'
import { Route as RuPaphosAirportTransfersRouteImport } from './routes/ru.paphos-airport-transfers'
import { Route as RuLarnacaAirportTransfersRouteImport } from './routes/ru.larnaca-airport-transfers'
import { Route as RuLarnacaAirportToPaphosRouteImport } from './routes/ru.larnaca-airport-to-paphos'
import { Route as RuFleetRouteImport } from './routes/ru.fleet'
import { Route as RuFaqRouteImport } from './routes/ru.faq'
import { Route as RuCyprusAirportTransfersRouteImport } from './routes/ru.cyprus-airport-transfers'
import { Route as RuContactRouteImport } from './routes/ru.contact'
import { Route as RuBlogRouteImport } from './routes/ru.blog'
import { Route as RuAboutRouteImport } from './routes/ru.about'
import { Route as RuSplatRouteImport } from './routes/ru.$'
import { Route as ElTaxiToPeyiaRouteImport } from './routes/el.taxi-to-peyia'
import { Route as ElTaxiToLimassolRouteImport } from './routes/el.taxi-to-limassol'
import { Route as ElTaxiToCoralBayRouteImport } from './routes/el.taxi-to-coral-bay'
import { Route as ElTaxiToChlorakaRouteImport } from './routes/el.taxi-to-chloraka'
import { Route as ElReviewsRouteImport } from './routes/el.reviews'
import { Route as ElPricingRouteImport } from './routes/el.pricing'
import { Route as ElPaphosAirportTransfersRouteImport } from './routes/el.paphos-airport-transfers'
import { Route as ElLarnacaAirportTransfersRouteImport } from './routes/el.larnaca-airport-transfers'
import { Route as ElLarnacaAirportToPaphosRouteImport } from './routes/el.larnaca-airport-to-paphos'
import { Route as ElFleetRouteImport } from './routes/el.fleet'
import { Route as ElFaqRouteImport } from './routes/el.faq'
import { Route as ElCyprusAirportTransfersRouteImport } from './routes/el.cyprus-airport-transfers'
import { Route as ElContactRouteImport } from './routes/el.contact'
import { Route as ElBlogRouteImport } from './routes/el.blog'
import { Route as ElAboutRouteImport } from './routes/el.about'
import { Route as BlogTopHotelsVillasCoralBayPeyiaRouteImport } from './routes/blog_.top-hotels-villas-coral-bay-peyia'
import { Route as BlogThingsToDoInPaphosRouteImport } from './routes/blog_.things-to-do-in-paphos'
import { Route as BlogLarnacaAirportToPaphosTravelGuideRouteImport } from './routes/blog_.larnaca-airport-to-paphos-travel-guide'
import { Route as BlogHiddenGemsChlorakaKissonergaRouteImport } from './routes/blog_.hidden-gems-chloraka-kissonerga'
import { Route as BlogCyprusTravelTipsFirstTimeVisitorsRouteImport } from './routes/blog_.cyprus-travel-tips-first-time-visitors'
import { Route as BlogCompleteCyprusAirportTransferGuideRouteImport } from './routes/blog_.complete-cyprus-airport-transfer-guide'
import { Route as BlogBestBeachesPaphosCoralBayRouteImport } from './routes/blog_.best-beaches-paphos-coral-bay'

const ZooInPaphosRoute = ZooInPaphosRouteImport.update({
  id: '/zoo-in-paphos',
  path: '/zoo-in-paphos',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiToPeyiaRoute = TaxiToPeyiaRouteImport.update({
  id: '/taxi-to-peyia',
  path: '/taxi-to-peyia',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiToLimassolRoute = TaxiToLimassolRouteImport.update({
  id: '/taxi-to-limassol',
  path: '/taxi-to-limassol',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiToCoralBayRoute = TaxiToCoralBayRouteImport.update({
  id: '/taxi-to-coral-bay',
  path: '/taxi-to-coral-bay',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiToChlorakaRoute = TaxiToChlorakaRouteImport.update({
  id: '/taxi-to-chloraka',
  path: '/taxi-to-chloraka',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaphosAirportTransfersRoute = PaphosAirportTransfersRouteImport.update({
  id: '/paphos-airport-transfers',
  path: '/paphos-airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const MercedesW213VipRoute = MercedesW213VipRouteImport.update({
  id: '/mercedes-w213-vip',
  path: '/mercedes-w213-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const LarnacaAirportTransfersRoute = LarnacaAirportTransfersRouteImport.update({
  id: '/larnaca-airport-transfers',
  path: '/larnaca-airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const LarnacaAirportToProtarasRoute =
  LarnacaAirportToProtarasRouteImport.update({
    id: '/larnaca-airport-to-protaras',
    path: '/larnaca-airport-to-protaras',
    getParentRoute: () => rootRouteImport,
  } as any)
const LarnacaAirportToPaphosRoute = LarnacaAirportToPaphosRouteImport.update({
  id: '/larnaca-airport-to-paphos',
  path: '/larnaca-airport-to-paphos',
  getParentRoute: () => rootRouteImport,
} as any)
const LarnacaAirportToAyiaNapaRoute =
  LarnacaAirportToAyiaNapaRouteImport.update({
    id: '/larnaca-airport-to-ayia-napa',
    path: '/larnaca-airport-to-ayia-napa',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexDotphpRoute = IndexDotphpRouteImport.update({
  id: '/index.php',
  path: '/index.php',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ElRoute = ElRouteImport.update({
  id: '/el',
  path: '/el',
  getParentRoute: () => rootRouteImport,
} as any)
const CyprusAirportTransfersRoute = CyprusAirportTransfersRouteImport.update({
  id: '/cyprus-airport-transfers',
  path: '/cyprus-airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuRoute,
} as any)
const ElIndexRoute = ElIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElRoute,
} as any)
const RuTaxiToPeyiaRoute = RuTaxiToPeyiaRouteImport.update({
  id: '/taxi-to-peyia',
  path: '/taxi-to-peyia',
  getParentRoute: () => RuRoute,
} as any)
const RuTaxiToLimassolRoute = RuTaxiToLimassolRouteImport.update({
  id: '/taxi-to-limassol',
  path: '/taxi-to-limassol',
  getParentRoute: () => RuRoute,
} as any)
const RuTaxiToCoralBayRoute = RuTaxiToCoralBayRouteImport.update({
  id: '/taxi-to-coral-bay',
  path: '/taxi-to-coral-bay',
  getParentRoute: () => RuRoute,
} as any)
const RuTaxiToChlorakaRoute = RuTaxiToChlorakaRouteImport.update({
  id: '/taxi-to-chloraka',
  path: '/taxi-to-chloraka',
  getParentRoute: () => RuRoute,
} as any)
const RuReviewsRoute = RuReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => RuRoute,
} as any)
const RuPricingRoute = RuPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => RuRoute,
} as any)
const RuPaphosAirportTransfersRoute =
  RuPaphosAirportTransfersRouteImport.update({
    id: '/paphos-airport-transfers',
    path: '/paphos-airport-transfers',
    getParentRoute: () => RuRoute,
  } as any)
const RuLarnacaAirportTransfersRoute =
  RuLarnacaAirportTransfersRouteImport.update({
    id: '/larnaca-airport-transfers',
    path: '/larnaca-airport-transfers',
    getParentRoute: () => RuRoute,
  } as any)
const RuLarnacaAirportToPaphosRoute =
  RuLarnacaAirportToPaphosRouteImport.update({
    id: '/larnaca-airport-to-paphos',
    path: '/larnaca-airport-to-paphos',
    getParentRoute: () => RuRoute,
  } as any)
const RuFleetRoute = RuFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => RuRoute,
} as any)
const RuFaqRoute = RuFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => RuRoute,
} as any)
const RuCyprusAirportTransfersRoute =
  RuCyprusAirportTransfersRouteImport.update({
    id: '/cyprus-airport-transfers',
    path: '/cyprus-airport-transfers',
    getParentRoute: () => RuRoute,
  } as any)
const RuContactRoute = RuContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => RuRoute,
} as any)
const RuBlogRoute = RuBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => RuRoute,
} as any)
const RuAboutRoute = RuAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RuRoute,
} as any)
const RuSplatRoute = RuSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RuRoute,
} as any)
const ElTaxiToPeyiaRoute = ElTaxiToPeyiaRouteImport.update({
  id: '/taxi-to-peyia',
  path: '/taxi-to-peyia',
  getParentRoute: () => ElRoute,
} as any)
const ElTaxiToLimassolRoute = ElTaxiToLimassolRouteImport.update({
  id: '/taxi-to-limassol',
  path: '/taxi-to-limassol',
  getParentRoute: () => ElRoute,
} as any)
const ElTaxiToCoralBayRoute = ElTaxiToCoralBayRouteImport.update({
  id: '/taxi-to-coral-bay',
  path: '/taxi-to-coral-bay',
  getParentRoute: () => ElRoute,
} as any)
const ElTaxiToChlorakaRoute = ElTaxiToChlorakaRouteImport.update({
  id: '/taxi-to-chloraka',
  path: '/taxi-to-chloraka',
  getParentRoute: () => ElRoute,
} as any)
const ElReviewsRoute = ElReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ElRoute,
} as any)
const ElPricingRoute = ElPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ElRoute,
} as any)
const ElPaphosAirportTransfersRoute =
  ElPaphosAirportTransfersRouteImport.update({
    id: '/paphos-airport-transfers',
    path: '/paphos-airport-transfers',
    getParentRoute: () => ElRoute,
  } as any)
const ElLarnacaAirportTransfersRoute =
  ElLarnacaAirportTransfersRouteImport.update({
    id: '/larnaca-airport-transfers',
    path: '/larnaca-airport-transfers',
    getParentRoute: () => ElRoute,
  } as any)
const ElLarnacaAirportToPaphosRoute =
  ElLarnacaAirportToPaphosRouteImport.update({
    id: '/larnaca-airport-to-paphos',
    path: '/larnaca-airport-to-paphos',
    getParentRoute: () => ElRoute,
  } as any)
const ElFleetRoute = ElFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => ElRoute,
} as any)
const ElFaqRoute = ElFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ElRoute,
} as any)
const ElCyprusAirportTransfersRoute =
  ElCyprusAirportTransfersRouteImport.update({
    id: '/cyprus-airport-transfers',
    path: '/cyprus-airport-transfers',
    getParentRoute: () => ElRoute,
  } as any)
const ElContactRoute = ElContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ElRoute,
} as any)
const ElBlogRoute = ElBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => ElRoute,
} as any)
const ElAboutRoute = ElAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ElRoute,
} as any)
const BlogTopHotelsVillasCoralBayPeyiaRoute =
  BlogTopHotelsVillasCoralBayPeyiaRouteImport.update({
    id: '/blog_/top-hotels-villas-coral-bay-peyia',
    path: '/blog/top-hotels-villas-coral-bay-peyia',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogThingsToDoInPaphosRoute = BlogThingsToDoInPaphosRouteImport.update({
  id: '/blog_/things-to-do-in-paphos',
  path: '/blog/things-to-do-in-paphos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLarnacaAirportToPaphosTravelGuideRoute =
  BlogLarnacaAirportToPaphosTravelGuideRouteImport.update({
    id: '/blog_/larnaca-airport-to-paphos-travel-guide',
    path: '/blog/larnaca-airport-to-paphos-travel-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHiddenGemsChlorakaKissonergaRoute =
  BlogHiddenGemsChlorakaKissonergaRouteImport.update({
    id: '/blog_/hidden-gems-chloraka-kissonerga',
    path: '/blog/hidden-gems-chloraka-kissonerga',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCyprusTravelTipsFirstTimeVisitorsRoute =
  BlogCyprusTravelTipsFirstTimeVisitorsRouteImport.update({
    id: '/blog_/cyprus-travel-tips-first-time-visitors',
    path: '/blog/cyprus-travel-tips-first-time-visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCompleteCyprusAirportTransferGuideRoute =
  BlogCompleteCyprusAirportTransferGuideRouteImport.update({
    id: '/blog_/complete-cyprus-airport-transfer-guide',
    path: '/blog/complete-cyprus-airport-transfer-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestBeachesPaphosCoralBayRoute =
  BlogBestBeachesPaphosCoralBayRouteImport.update({
    id: '/blog_/best-beaches-paphos-coral-bay',
    path: '/blog/best-beaches-paphos-coral-bay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cyprus-airport-transfers': typeof CyprusAirportTransfersRoute
  '/el': typeof ElRouteWithChildren
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/index.php': typeof IndexDotphpRoute
  '/larnaca-airport-to-ayia-napa': typeof LarnacaAirportToAyiaNapaRoute
  '/larnaca-airport-to-paphos': typeof LarnacaAirportToPaphosRoute
  '/larnaca-airport-to-protaras': typeof LarnacaAirportToProtarasRoute
  '/larnaca-airport-transfers': typeof LarnacaAirportTransfersRoute
  '/mercedes-w213-vip': typeof MercedesW213VipRoute
  '/paphos-airport-transfers': typeof PaphosAirportTransfersRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taxi-to-chloraka': typeof TaxiToChlorakaRoute
  '/taxi-to-coral-bay': typeof TaxiToCoralBayRoute
  '/taxi-to-limassol': typeof TaxiToLimassolRoute
  '/taxi-to-peyia': typeof TaxiToPeyiaRoute
  '/zoo-in-paphos': typeof ZooInPaphosRoute
  '/blog/best-beaches-paphos-coral-bay': typeof BlogBestBeachesPaphosCoralBayRoute
  '/blog/complete-cyprus-airport-transfer-guide': typeof BlogCompleteCyprusAirportTransferGuideRoute
  '/blog/cyprus-travel-tips-first-time-visitors': typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  '/blog/hidden-gems-chloraka-kissonerga': typeof BlogHiddenGemsChlorakaKissonergaRoute
  '/blog/larnaca-airport-to-paphos-travel-guide': typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  '/blog/things-to-do-in-paphos': typeof BlogThingsToDoInPaphosRoute
  '/blog/top-hotels-villas-coral-bay-peyia': typeof BlogTopHotelsVillasCoralBayPeyiaRoute
  '/el/about': typeof ElAboutRoute
  '/el/blog': typeof ElBlogRoute
  '/el/contact': typeof ElContactRoute
  '/el/cyprus-airport-transfers': typeof ElCyprusAirportTransfersRoute
  '/el/faq': typeof ElFaqRoute
  '/el/fleet': typeof ElFleetRoute
  '/el/larnaca-airport-to-paphos': typeof ElLarnacaAirportToPaphosRoute
  '/el/larnaca-airport-transfers': typeof ElLarnacaAirportTransfersRoute
  '/el/paphos-airport-transfers': typeof ElPaphosAirportTransfersRoute
  '/el/pricing': typeof ElPricingRoute
  '/el/reviews': typeof ElReviewsRoute
  '/el/taxi-to-chloraka': typeof ElTaxiToChlorakaRoute
  '/el/taxi-to-coral-bay': typeof ElTaxiToCoralBayRoute
  '/el/taxi-to-limassol': typeof ElTaxiToLimassolRoute
  '/el/taxi-to-peyia': typeof ElTaxiToPeyiaRoute
  '/ru/$': typeof RuSplatRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRoute
  '/ru/contact': typeof RuContactRoute
  '/ru/cyprus-airport-transfers': typeof RuCyprusAirportTransfersRoute
  '/ru/faq': typeof RuFaqRoute
  '/ru/fleet': typeof RuFleetRoute
  '/ru/larnaca-airport-to-paphos': typeof RuLarnacaAirportToPaphosRoute
  '/ru/larnaca-airport-transfers': typeof RuLarnacaAirportTransfersRoute
  '/ru/paphos-airport-transfers': typeof RuPaphosAirportTransfersRoute
  '/ru/pricing': typeof RuPricingRoute
  '/ru/reviews': typeof RuReviewsRoute
  '/ru/taxi-to-chloraka': typeof RuTaxiToChlorakaRoute
  '/ru/taxi-to-coral-bay': typeof RuTaxiToCoralBayRoute
  '/ru/taxi-to-limassol': typeof RuTaxiToLimassolRoute
  '/ru/taxi-to-peyia': typeof RuTaxiToPeyiaRoute
  '/el/': typeof ElIndexRoute
  '/ru/': typeof RuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cyprus-airport-transfers': typeof CyprusAirportTransfersRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/index.php': typeof IndexDotphpRoute
  '/larnaca-airport-to-ayia-napa': typeof LarnacaAirportToAyiaNapaRoute
  '/larnaca-airport-to-paphos': typeof LarnacaAirportToPaphosRoute
  '/larnaca-airport-to-protaras': typeof LarnacaAirportToProtarasRoute
  '/larnaca-airport-transfers': typeof LarnacaAirportTransfersRoute
  '/mercedes-w213-vip': typeof MercedesW213VipRoute
  '/paphos-airport-transfers': typeof PaphosAirportTransfersRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taxi-to-chloraka': typeof TaxiToChlorakaRoute
  '/taxi-to-coral-bay': typeof TaxiToCoralBayRoute
  '/taxi-to-limassol': typeof TaxiToLimassolRoute
  '/taxi-to-peyia': typeof TaxiToPeyiaRoute
  '/zoo-in-paphos': typeof ZooInPaphosRoute
  '/blog/best-beaches-paphos-coral-bay': typeof BlogBestBeachesPaphosCoralBayRoute
  '/blog/complete-cyprus-airport-transfer-guide': typeof BlogCompleteCyprusAirportTransferGuideRoute
  '/blog/cyprus-travel-tips-first-time-visitors': typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  '/blog/hidden-gems-chloraka-kissonerga': typeof BlogHiddenGemsChlorakaKissonergaRoute
  '/blog/larnaca-airport-to-paphos-travel-guide': typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  '/blog/things-to-do-in-paphos': typeof BlogThingsToDoInPaphosRoute
  '/blog/top-hotels-villas-coral-bay-peyia': typeof BlogTopHotelsVillasCoralBayPeyiaRoute
  '/el/about': typeof ElAboutRoute
  '/el/blog': typeof ElBlogRoute
  '/el/contact': typeof ElContactRoute
  '/el/cyprus-airport-transfers': typeof ElCyprusAirportTransfersRoute
  '/el/faq': typeof ElFaqRoute
  '/el/fleet': typeof ElFleetRoute
  '/el/larnaca-airport-to-paphos': typeof ElLarnacaAirportToPaphosRoute
  '/el/larnaca-airport-transfers': typeof ElLarnacaAirportTransfersRoute
  '/el/paphos-airport-transfers': typeof ElPaphosAirportTransfersRoute
  '/el/pricing': typeof ElPricingRoute
  '/el/reviews': typeof ElReviewsRoute
  '/el/taxi-to-chloraka': typeof ElTaxiToChlorakaRoute
  '/el/taxi-to-coral-bay': typeof ElTaxiToCoralBayRoute
  '/el/taxi-to-limassol': typeof ElTaxiToLimassolRoute
  '/el/taxi-to-peyia': typeof ElTaxiToPeyiaRoute
  '/ru/$': typeof RuSplatRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRoute
  '/ru/contact': typeof RuContactRoute
  '/ru/cyprus-airport-transfers': typeof RuCyprusAirportTransfersRoute
  '/ru/faq': typeof RuFaqRoute
  '/ru/fleet': typeof RuFleetRoute
  '/ru/larnaca-airport-to-paphos': typeof RuLarnacaAirportToPaphosRoute
  '/ru/larnaca-airport-transfers': typeof RuLarnacaAirportTransfersRoute
  '/ru/paphos-airport-transfers': typeof RuPaphosAirportTransfersRoute
  '/ru/pricing': typeof RuPricingRoute
  '/ru/reviews': typeof RuReviewsRoute
  '/ru/taxi-to-chloraka': typeof RuTaxiToChlorakaRoute
  '/ru/taxi-to-coral-bay': typeof RuTaxiToCoralBayRoute
  '/ru/taxi-to-limassol': typeof RuTaxiToLimassolRoute
  '/ru/taxi-to-peyia': typeof RuTaxiToPeyiaRoute
  '/el': typeof ElIndexRoute
  '/ru': typeof RuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/cyprus-airport-transfers': typeof CyprusAirportTransfersRoute
  '/el': typeof ElRouteWithChildren
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRoute
  '/index.php': typeof IndexDotphpRoute
  '/larnaca-airport-to-ayia-napa': typeof LarnacaAirportToAyiaNapaRoute
  '/larnaca-airport-to-paphos': typeof LarnacaAirportToPaphosRoute
  '/larnaca-airport-to-protaras': typeof LarnacaAirportToProtarasRoute
  '/larnaca-airport-transfers': typeof LarnacaAirportTransfersRoute
  '/mercedes-w213-vip': typeof MercedesW213VipRoute
  '/paphos-airport-transfers': typeof PaphosAirportTransfersRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/ru': typeof RuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taxi-to-chloraka': typeof TaxiToChlorakaRoute
  '/taxi-to-coral-bay': typeof TaxiToCoralBayRoute
  '/taxi-to-limassol': typeof TaxiToLimassolRoute
  '/taxi-to-peyia': typeof TaxiToPeyiaRoute
  '/zoo-in-paphos': typeof ZooInPaphosRoute
  '/blog_/best-beaches-paphos-coral-bay': typeof BlogBestBeachesPaphosCoralBayRoute
  '/blog_/complete-cyprus-airport-transfer-guide': typeof BlogCompleteCyprusAirportTransferGuideRoute
  '/blog_/cyprus-travel-tips-first-time-visitors': typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  '/blog_/hidden-gems-chloraka-kissonerga': typeof BlogHiddenGemsChlorakaKissonergaRoute
  '/blog_/larnaca-airport-to-paphos-travel-guide': typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  '/blog_/things-to-do-in-paphos': typeof BlogThingsToDoInPaphosRoute
  '/blog_/top-hotels-villas-coral-bay-peyia': typeof BlogTopHotelsVillasCoralBayPeyiaRoute
  '/el/about': typeof ElAboutRoute
  '/el/blog': typeof ElBlogRoute
  '/el/contact': typeof ElContactRoute
  '/el/cyprus-airport-transfers': typeof ElCyprusAirportTransfersRoute
  '/el/faq': typeof ElFaqRoute
  '/el/fleet': typeof ElFleetRoute
  '/el/larnaca-airport-to-paphos': typeof ElLarnacaAirportToPaphosRoute
  '/el/larnaca-airport-transfers': typeof ElLarnacaAirportTransfersRoute
  '/el/paphos-airport-transfers': typeof ElPaphosAirportTransfersRoute
  '/el/pricing': typeof ElPricingRoute
  '/el/reviews': typeof ElReviewsRoute
  '/el/taxi-to-chloraka': typeof ElTaxiToChlorakaRoute
  '/el/taxi-to-coral-bay': typeof ElTaxiToCoralBayRoute
  '/el/taxi-to-limassol': typeof ElTaxiToLimassolRoute
  '/el/taxi-to-peyia': typeof ElTaxiToPeyiaRoute
  '/ru/$': typeof RuSplatRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRoute
  '/ru/contact': typeof RuContactRoute
  '/ru/cyprus-airport-transfers': typeof RuCyprusAirportTransfersRoute
  '/ru/faq': typeof RuFaqRoute
  '/ru/fleet': typeof RuFleetRoute
  '/ru/larnaca-airport-to-paphos': typeof RuLarnacaAirportToPaphosRoute
  '/ru/larnaca-airport-transfers': typeof RuLarnacaAirportTransfersRoute
  '/ru/paphos-airport-transfers': typeof RuPaphosAirportTransfersRoute
  '/ru/pricing': typeof RuPricingRoute
  '/ru/reviews': typeof RuReviewsRoute
  '/ru/taxi-to-chloraka': typeof RuTaxiToChlorakaRoute
  '/ru/taxi-to-coral-bay': typeof RuTaxiToCoralBayRoute
  '/ru/taxi-to-limassol': typeof RuTaxiToLimassolRoute
  '/ru/taxi-to-peyia': typeof RuTaxiToPeyiaRoute
  '/el/': typeof ElIndexRoute
  '/ru/': typeof RuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cyprus-airport-transfers'
    | '/el'
    | '/faq'
    | '/fleet'
    | '/index.php'
    | '/larnaca-airport-to-ayia-napa'
    | '/larnaca-airport-to-paphos'
    | '/larnaca-airport-to-protaras'
    | '/larnaca-airport-transfers'
    | '/mercedes-w213-vip'
    | '/paphos-airport-transfers'
    | '/pricing'
    | '/reviews'
    | '/ru'
    | '/sitemap.xml'
    | '/taxi-to-chloraka'
    | '/taxi-to-coral-bay'
    | '/taxi-to-limassol'
    | '/taxi-to-peyia'
    | '/zoo-in-paphos'
    | '/blog/best-beaches-paphos-coral-bay'
    | '/blog/complete-cyprus-airport-transfer-guide'
    | '/blog/cyprus-travel-tips-first-time-visitors'
    | '/blog/hidden-gems-chloraka-kissonerga'
    | '/blog/larnaca-airport-to-paphos-travel-guide'
    | '/blog/things-to-do-in-paphos'
    | '/blog/top-hotels-villas-coral-bay-peyia'
    | '/el/about'
    | '/el/blog'
    | '/el/contact'
    | '/el/cyprus-airport-transfers'
    | '/el/faq'
    | '/el/fleet'
    | '/el/larnaca-airport-to-paphos'
    | '/el/larnaca-airport-transfers'
    | '/el/paphos-airport-transfers'
    | '/el/pricing'
    | '/el/reviews'
    | '/el/taxi-to-chloraka'
    | '/el/taxi-to-coral-bay'
    | '/el/taxi-to-limassol'
    | '/el/taxi-to-peyia'
    | '/ru/$'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/contact'
    | '/ru/cyprus-airport-transfers'
    | '/ru/faq'
    | '/ru/fleet'
    | '/ru/larnaca-airport-to-paphos'
    | '/ru/larnaca-airport-transfers'
    | '/ru/paphos-airport-transfers'
    | '/ru/pricing'
    | '/ru/reviews'
    | '/ru/taxi-to-chloraka'
    | '/ru/taxi-to-coral-bay'
    | '/ru/taxi-to-limassol'
    | '/ru/taxi-to-peyia'
    | '/el/'
    | '/ru/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cyprus-airport-transfers'
    | '/faq'
    | '/fleet'
    | '/index.php'
    | '/larnaca-airport-to-ayia-napa'
    | '/larnaca-airport-to-paphos'
    | '/larnaca-airport-to-protaras'
    | '/larnaca-airport-transfers'
    | '/mercedes-w213-vip'
    | '/paphos-airport-transfers'
    | '/pricing'
    | '/reviews'
    | '/sitemap.xml'
    | '/taxi-to-chloraka'
    | '/taxi-to-coral-bay'
    | '/taxi-to-limassol'
    | '/taxi-to-peyia'
    | '/zoo-in-paphos'
    | '/blog/best-beaches-paphos-coral-bay'
    | '/blog/complete-cyprus-airport-transfer-guide'
    | '/blog/cyprus-travel-tips-first-time-visitors'
    | '/blog/hidden-gems-chloraka-kissonerga'
    | '/blog/larnaca-airport-to-paphos-travel-guide'
    | '/blog/things-to-do-in-paphos'
    | '/blog/top-hotels-villas-coral-bay-peyia'
    | '/el/about'
    | '/el/blog'
    | '/el/contact'
    | '/el/cyprus-airport-transfers'
    | '/el/faq'
    | '/el/fleet'
    | '/el/larnaca-airport-to-paphos'
    | '/el/larnaca-airport-transfers'
    | '/el/paphos-airport-transfers'
    | '/el/pricing'
    | '/el/reviews'
    | '/el/taxi-to-chloraka'
    | '/el/taxi-to-coral-bay'
    | '/el/taxi-to-limassol'
    | '/el/taxi-to-peyia'
    | '/ru/$'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/contact'
    | '/ru/cyprus-airport-transfers'
    | '/ru/faq'
    | '/ru/fleet'
    | '/ru/larnaca-airport-to-paphos'
    | '/ru/larnaca-airport-transfers'
    | '/ru/paphos-airport-transfers'
    | '/ru/pricing'
    | '/ru/reviews'
    | '/ru/taxi-to-chloraka'
    | '/ru/taxi-to-coral-bay'
    | '/ru/taxi-to-limassol'
    | '/ru/taxi-to-peyia'
    | '/el'
    | '/ru'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cyprus-airport-transfers'
    | '/el'
    | '/faq'
    | '/fleet'
    | '/index.php'
    | '/larnaca-airport-to-ayia-napa'
    | '/larnaca-airport-to-paphos'
    | '/larnaca-airport-to-protaras'
    | '/larnaca-airport-transfers'
    | '/mercedes-w213-vip'
    | '/paphos-airport-transfers'
    | '/pricing'
    | '/reviews'
    | '/ru'
    | '/sitemap.xml'
    | '/taxi-to-chloraka'
    | '/taxi-to-coral-bay'
    | '/taxi-to-limassol'
    | '/taxi-to-peyia'
    | '/zoo-in-paphos'
    | '/blog_/best-beaches-paphos-coral-bay'
    | '/blog_/complete-cyprus-airport-transfer-guide'
    | '/blog_/cyprus-travel-tips-first-time-visitors'
    | '/blog_/hidden-gems-chloraka-kissonerga'
    | '/blog_/larnaca-airport-to-paphos-travel-guide'
    | '/blog_/things-to-do-in-paphos'
    | '/blog_/top-hotels-villas-coral-bay-peyia'
    | '/el/about'
    | '/el/blog'
    | '/el/contact'
    | '/el/cyprus-airport-transfers'
    | '/el/faq'
    | '/el/fleet'
    | '/el/larnaca-airport-to-paphos'
    | '/el/larnaca-airport-transfers'
    | '/el/paphos-airport-transfers'
    | '/el/pricing'
    | '/el/reviews'
    | '/el/taxi-to-chloraka'
    | '/el/taxi-to-coral-bay'
    | '/el/taxi-to-limassol'
    | '/el/taxi-to-peyia'
    | '/ru/$'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/contact'
    | '/ru/cyprus-airport-transfers'
    | '/ru/faq'
    | '/ru/fleet'
    | '/ru/larnaca-airport-to-paphos'
    | '/ru/larnaca-airport-transfers'
    | '/ru/paphos-airport-transfers'
    | '/ru/pricing'
    | '/ru/reviews'
    | '/ru/taxi-to-chloraka'
    | '/ru/taxi-to-coral-bay'
    | '/ru/taxi-to-limassol'
    | '/ru/taxi-to-peyia'
    | '/el/'
    | '/ru/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CyprusAirportTransfersRoute: typeof CyprusAirportTransfersRoute
  ElRoute: typeof ElRouteWithChildren
  FaqRoute: typeof FaqRoute
  FleetRoute: typeof FleetRoute
  IndexDotphpRoute: typeof IndexDotphpRoute
  LarnacaAirportToAyiaNapaRoute: typeof LarnacaAirportToAyiaNapaRoute
  LarnacaAirportToPaphosRoute: typeof LarnacaAirportToPaphosRoute
  LarnacaAirportToProtarasRoute: typeof LarnacaAirportToProtarasRoute
  LarnacaAirportTransfersRoute: typeof LarnacaAirportTransfersRoute
  MercedesW213VipRoute: typeof MercedesW213VipRoute
  PaphosAirportTransfersRoute: typeof PaphosAirportTransfersRoute
  PricingRoute: typeof PricingRoute
  ReviewsRoute: typeof ReviewsRoute
  RuRoute: typeof RuRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaxiToChlorakaRoute: typeof TaxiToChlorakaRoute
  TaxiToCoralBayRoute: typeof TaxiToCoralBayRoute
  TaxiToLimassolRoute: typeof TaxiToLimassolRoute
  TaxiToPeyiaRoute: typeof TaxiToPeyiaRoute
  ZooInPaphosRoute: typeof ZooInPaphosRoute
  BlogBestBeachesPaphosCoralBayRoute: typeof BlogBestBeachesPaphosCoralBayRoute
  BlogCompleteCyprusAirportTransferGuideRoute: typeof BlogCompleteCyprusAirportTransferGuideRoute
  BlogCyprusTravelTipsFirstTimeVisitorsRoute: typeof BlogCyprusTravelTipsFirstTimeVisitorsRoute
  BlogHiddenGemsChlorakaKissonergaRoute: typeof BlogHiddenGemsChlorakaKissonergaRoute
  BlogLarnacaAirportToPaphosTravelGuideRoute: typeof BlogLarnacaAirportToPaphosTravelGuideRoute
  BlogThingsToDoInPaphosRoute: typeof BlogThingsToDoInPaphosRoute
  BlogTopHotelsVillasCoralBayPeyiaRoute: typeof BlogTopHotelsVillasCoralBayPeyiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoo-in-paphos': {
      id: '/zoo-in-paphos'
      path: '/zoo-in-paphos'
      fullPath: '/zoo-in-paphos'
      preLoaderRoute: typeof ZooInPaphosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-to-peyia': {
      id: '/taxi-to-peyia'
      path: '/taxi-to-peyia'
      fullPath: '/taxi-to-peyia'
      preLoaderRoute: typeof TaxiToPeyiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-to-limassol': {
      id: '/taxi-to-limassol'
      path: '/taxi-to-limassol'
      fullPath: '/taxi-to-limassol'
      preLoaderRoute: typeof TaxiToLimassolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-to-coral-bay': {
      id: '/taxi-to-coral-bay'
      path: '/taxi-to-coral-bay'
      fullPath: '/taxi-to-coral-bay'
      preLoaderRoute: typeof TaxiToCoralBayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-to-chloraka': {
      id: '/taxi-to-chloraka'
      path: '/taxi-to-chloraka'
      fullPath: '/taxi-to-chloraka'
      preLoaderRoute: typeof TaxiToChlorakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paphos-airport-transfers': {
      id: '/paphos-airport-transfers'
      path: '/paphos-airport-transfers'
      fullPath: '/paphos-airport-transfers'
      preLoaderRoute: typeof PaphosAirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercedes-w213-vip': {
      id: '/mercedes-w213-vip'
      path: '/mercedes-w213-vip'
      fullPath: '/mercedes-w213-vip'
      preLoaderRoute: typeof MercedesW213VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/larnaca-airport-transfers': {
      id: '/larnaca-airport-transfers'
      path: '/larnaca-airport-transfers'
      fullPath: '/larnaca-airport-transfers'
      preLoaderRoute: typeof LarnacaAirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/larnaca-airport-to-protaras': {
      id: '/larnaca-airport-to-protaras'
      path: '/larnaca-airport-to-protaras'
      fullPath: '/larnaca-airport-to-protaras'
      preLoaderRoute: typeof LarnacaAirportToProtarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/larnaca-airport-to-paphos': {
      id: '/larnaca-airport-to-paphos'
      path: '/larnaca-airport-to-paphos'
      fullPath: '/larnaca-airport-to-paphos'
      preLoaderRoute: typeof LarnacaAirportToPaphosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/larnaca-airport-to-ayia-napa': {
      id: '/larnaca-airport-to-ayia-napa'
      path: '/larnaca-airport-to-ayia-napa'
      fullPath: '/larnaca-airport-to-ayia-napa'
      preLoaderRoute: typeof LarnacaAirportToAyiaNapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.php': {
      id: '/index.php'
      path: '/index.php'
      fullPath: '/index.php'
      preLoaderRoute: typeof IndexDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el': {
      id: '/el'
      path: '/el'
      fullPath: '/el'
      preLoaderRoute: typeof ElRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyprus-airport-transfers': {
      id: '/cyprus-airport-transfers'
      path: '/cyprus-airport-transfers'
      fullPath: '/cyprus-airport-transfers'
      preLoaderRoute: typeof CyprusAirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof RuRoute
    }
    '/el/': {
      id: '/el/'
      path: '/'
      fullPath: '/el/'
      preLoaderRoute: typeof ElIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/ru/taxi-to-peyia': {
      id: '/ru/taxi-to-peyia'
      path: '/taxi-to-peyia'
      fullPath: '/ru/taxi-to-peyia'
      preLoaderRoute: typeof RuTaxiToPeyiaRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/taxi-to-limassol': {
      id: '/ru/taxi-to-limassol'
      path: '/taxi-to-limassol'
      fullPath: '/ru/taxi-to-limassol'
      preLoaderRoute: typeof RuTaxiToLimassolRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/taxi-to-coral-bay': {
      id: '/ru/taxi-to-coral-bay'
      path: '/taxi-to-coral-bay'
      fullPath: '/ru/taxi-to-coral-bay'
      preLoaderRoute: typeof RuTaxiToCoralBayRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/taxi-to-chloraka': {
      id: '/ru/taxi-to-chloraka'
      path: '/taxi-to-chloraka'
      fullPath: '/ru/taxi-to-chloraka'
      preLoaderRoute: typeof RuTaxiToChlorakaRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/reviews': {
      id: '/ru/reviews'
      path: '/reviews'
      fullPath: '/ru/reviews'
      preLoaderRoute: typeof RuReviewsRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/pricing': {
      id: '/ru/pricing'
      path: '/pricing'
      fullPath: '/ru/pricing'
      preLoaderRoute: typeof RuPricingRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/paphos-airport-transfers': {
      id: '/ru/paphos-airport-transfers'
      path: '/paphos-airport-transfers'
      fullPath: '/ru/paphos-airport-transfers'
      preLoaderRoute: typeof RuPaphosAirportTransfersRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/larnaca-airport-transfers': {
      id: '/ru/larnaca-airport-transfers'
      path: '/larnaca-airport-transfers'
      fullPath: '/ru/larnaca-airport-transfers'
      preLoaderRoute: typeof RuLarnacaAirportTransfersRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/larnaca-airport-to-paphos': {
      id: '/ru/larnaca-airport-to-paphos'
      path: '/larnaca-airport-to-paphos'
      fullPath: '/ru/larnaca-airport-to-paphos'
      preLoaderRoute: typeof RuLarnacaAirportToPaphosRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/fleet': {
      id: '/ru/fleet'
      path: '/fleet'
      fullPath: '/ru/fleet'
      preLoaderRoute: typeof RuFleetRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/faq': {
      id: '/ru/faq'
      path: '/faq'
      fullPath: '/ru/faq'
      preLoaderRoute: typeof RuFaqRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/cyprus-airport-transfers': {
      id: '/ru/cyprus-airport-transfers'
      path: '/cyprus-airport-transfers'
      fullPath: '/ru/cyprus-airport-transfers'
      preLoaderRoute: typeof RuCyprusAirportTransfersRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/contact': {
      id: '/ru/contact'
      path: '/contact'
      fullPath: '/ru/contact'
      preLoaderRoute: typeof RuContactRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/blog': {
      id: '/ru/blog'
      path: '/blog'
      fullPath: '/ru/blog'
      preLoaderRoute: typeof RuBlogRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/about': {
      id: '/ru/about'
      path: '/about'
      fullPath: '/ru/about'
      preLoaderRoute: typeof RuAboutRouteImport
      parentRoute: typeof RuRoute
    }
    '/ru/$': {
      id: '/ru/$'
      path: '/$'
      fullPath: '/ru/$'
      preLoaderRoute: typeof RuSplatRouteImport
      parentRoute: typeof RuRoute
    }
    '/el/taxi-to-peyia': {
      id: '/el/taxi-to-peyia'
      path: '/taxi-to-peyia'
      fullPath: '/el/taxi-to-peyia'
      preLoaderRoute: typeof ElTaxiToPeyiaRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/taxi-to-limassol': {
      id: '/el/taxi-to-limassol'
      path: '/taxi-to-limassol'
      fullPath: '/el/taxi-to-limassol'
      preLoaderRoute: typeof ElTaxiToLimassolRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/taxi-to-coral-bay': {
      id: '/el/taxi-to-coral-bay'
      path: '/taxi-to-coral-bay'
      fullPath: '/el/taxi-to-coral-bay'
      preLoaderRoute: typeof ElTaxiToCoralBayRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/taxi-to-chloraka': {
      id: '/el/taxi-to-chloraka'
      path: '/taxi-to-chloraka'
      fullPath: '/el/taxi-to-chloraka'
      preLoaderRoute: typeof ElTaxiToChlorakaRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/reviews': {
      id: '/el/reviews'
      path: '/reviews'
      fullPath: '/el/reviews'
      preLoaderRoute: typeof ElReviewsRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/pricing': {
      id: '/el/pricing'
      path: '/pricing'
      fullPath: '/el/pricing'
      preLoaderRoute: typeof ElPricingRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/paphos-airport-transfers': {
      id: '/el/paphos-airport-transfers'
      path: '/paphos-airport-transfers'
      fullPath: '/el/paphos-airport-transfers'
      preLoaderRoute: typeof ElPaphosAirportTransfersRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/larnaca-airport-transfers': {
      id: '/el/larnaca-airport-transfers'
      path: '/larnaca-airport-transfers'
      fullPath: '/el/larnaca-airport-transfers'
      preLoaderRoute: typeof ElLarnacaAirportTransfersRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/larnaca-airport-to-paphos': {
      id: '/el/larnaca-airport-to-paphos'
      path: '/larnaca-airport-to-paphos'
      fullPath: '/el/larnaca-airport-to-paphos'
      preLoaderRoute: typeof ElLarnacaAirportToPaphosRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/fleet': {
      id: '/el/fleet'
      path: '/fleet'
      fullPath: '/el/fleet'
      preLoaderRoute: typeof ElFleetRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/faq': {
      id: '/el/faq'
      path: '/faq'
      fullPath: '/el/faq'
      preLoaderRoute: typeof ElFaqRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/cyprus-airport-transfers': {
      id: '/el/cyprus-airport-transfers'
      path: '/cyprus-airport-transfers'
      fullPath: '/el/cyprus-airport-transfers'
      preLoaderRoute: typeof ElCyprusAirportTransfersRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/contact': {
      id: '/el/contact'
      path: '/contact'
      fullPath: '/el/contact'
      preLoaderRoute: typeof ElContactRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/blog': {
      id: '/el/blog'
      path: '/blog'
      fullPath: '/el/blog'
      preLoaderRoute: typeof ElBlogRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/about': {
      id: '/el/about'
      path: '/about'
      fullPath: '/el/about'
      preLoaderRoute: typeof ElAboutRouteImport
      parentRoute: typeof ElRoute
    }
    '/blog_/top-hotels-villas-coral-bay-peyia': {
      id: '/blog_/top-hotels-villas-coral-bay-peyia'
      path: '/blog/top-hotels-villas-coral-bay-peyia'
      fullPath: '/blog/top-hotels-villas-coral-bay-peyia'
      preLoaderRoute: typeof BlogTopHotelsVillasCoralBayPeyiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/things-to-do-in-paphos': {
      id: '/blog_/things-to-do-in-paphos'
      path: '/blog/things-to-do-in-paphos'
      fullPath: '/blog/things-to-do-in-paphos'
      preLoaderRoute: typeof BlogThingsToDoInPaphosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/larnaca-airport-to-paphos-travel-guide': {
      id: '/blog_/larnaca-airport-to-paphos-travel-guide'
      path: '/blog/larnaca-airport-to-paphos-travel-guide'
      fullPath: '/blog/larnaca-airport-to-paphos-travel-guide'
      preLoaderRoute: typeof BlogLarnacaAirportToPaphosTravelGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/hidden-gems-chloraka-kissonerga': {
      id: '/blog_/hidden-gems-chloraka-kissonerga'
      path: '/blog/hidden-gems-chloraka-kissonerga'
      fullPath: '/blog/hidden-gems-chloraka-kissonerga'
      preLoaderRoute: typeof BlogHiddenGemsChlorakaKissonergaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/cyprus-travel-tips-first-time-visitors': {
      id: '/blog_/cyprus-travel-tips-first-time-visitors'
      path: '/blog/cyprus-travel-tips-first-time-visitors'
      fullPath: '/blog/cyprus-travel-tips-first-time-visitors'
      preLoaderRoute: typeof BlogCyprusTravelTipsFirstTimeVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/complete-cyprus-airport-transfer-guide': {
      id: '/blog_/complete-cyprus-airport-transfer-guide'
      path: '/blog/complete-cyprus-airport-transfer-guide'
      fullPath: '/blog/complete-cyprus-airport-transfer-guide'
      preLoaderRoute: typeof BlogCompleteCyprusAirportTransferGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/best-beaches-paphos-coral-bay': {
      id: '/blog_/best-beaches-paphos-coral-bay'
      path: '/blog/best-beaches-paphos-coral-bay'
      fullPath: '/blog/best-beaches-paphos-coral-bay'
      preLoaderRoute: typeof BlogBestBeachesPaphosCoralBayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElRouteChildren {
  ElAboutRoute: typeof ElAboutRoute
  ElBlogRoute: typeof ElBlogRoute
  ElContactRoute: typeof ElContactRoute
  ElCyprusAirportTransfersRoute: typeof ElCyprusAirportTransfersRoute
  ElFaqRoute: typeof ElFaqRoute
  ElFleetRoute: typeof ElFleetRoute
  ElLarnacaAirportToPaphosRoute: typeof ElLarnacaAirportToPaphosRoute
  ElLarnacaAirportTransfersRoute: typeof ElLarnacaAirportTransfersRoute
  ElPaphosAirportTransfersRoute: typeof ElPaphosAirportTransfersRoute
  ElPricingRoute: typeof ElPricingRoute
  ElReviewsRoute: typeof ElReviewsRoute
  ElTaxiToChlorakaRoute: typeof ElTaxiToChlorakaRoute
  ElTaxiToCoralBayRoute: typeof ElTaxiToCoralBayRoute
  ElTaxiToLimassolRoute: typeof ElTaxiToLimassolRoute
  ElTaxiToPeyiaRoute: typeof ElTaxiToPeyiaRoute
  ElIndexRoute: typeof ElIndexRoute
}

const ElRouteChildren: ElRouteChildren = {
  ElAboutRoute: ElAboutRoute,
  ElBlogRoute: ElBlogRoute,
  ElContactRoute: ElContactRoute,
  ElCyprusAirportTransfersRoute: ElCyprusAirportTransfersRoute,
  ElFaqRoute: ElFaqRoute,
  ElFleetRoute: ElFleetRoute,
  ElLarnacaAirportToPaphosRoute: ElLarnacaAirportToPaphosRoute,
  ElLarnacaAirportTransfersRoute: ElLarnacaAirportTransfersRoute,
  ElPaphosAirportTransfersRoute: ElPaphosAirportTransfersRoute,
  ElPricingRoute: ElPricingRoute,
  ElReviewsRoute: ElReviewsRoute,
  ElTaxiToChlorakaRoute: ElTaxiToChlorakaRoute,
  ElTaxiToCoralBayRoute: ElTaxiToCoralBayRoute,
  ElTaxiToLimassolRoute: ElTaxiToLimassolRoute,
  ElTaxiToPeyiaRoute: ElTaxiToPeyiaRoute,
  ElIndexRoute: ElIndexRoute,
}

const ElRouteWithChildren = ElRoute._addFileChildren(ElRouteChildren)

interface RuRouteChildren {
  RuSplatRoute: typeof RuSplatRoute
  RuAboutRoute: typeof RuAboutRoute
  RuBlogRoute: typeof RuBlogRoute
  RuContactRoute: typeof RuContactRoute
  RuCyprusAirportTransfersRoute: typeof RuCyprusAirportTransfersRoute
  RuFaqRoute: typeof RuFaqRoute
  RuFleetRoute: typeof RuFleetRoute
  RuLarnacaAirportToPaphosRoute: typeof RuLarnacaAirportToPaphosRoute
  RuLarnacaAirportTransfersRoute: typeof RuLarnacaAirportTransfersRoute
  RuPaphosAirportTransfersRoute: typeof RuPaphosAirportTransfersRoute
  RuPricingRoute: typeof RuPricingRoute
  RuReviewsRoute: typeof RuReviewsRoute
  RuTaxiToChlorakaRoute: typeof RuTaxiToChlorakaRoute
  RuTaxiToCoralBayRoute: typeof RuTaxiToCoralBayRoute
  RuTaxiToLimassolRoute: typeof RuTaxiToLimassolRoute
  RuTaxiToPeyiaRoute: typeof RuTaxiToPeyiaRoute
  RuIndexRoute: typeof RuIndexRoute
}

const RuRouteChildren: RuRouteChildren = {
  RuSplatRoute: RuSplatRoute,
  RuAboutRoute: RuAboutRoute,
  RuBlogRoute: RuBlogRoute,
  RuContactRoute: RuContactRoute,
  RuCyprusAirportTransfersRoute: RuCyprusAirportTransfersRoute,
  RuFaqRoute: RuFaqRoute,
  RuFleetRoute: RuFleetRoute,
  RuLarnacaAirportToPaphosRoute: RuLarnacaAirportToPaphosRoute,
  RuLarnacaAirportTransfersRoute: RuLarnacaAirportTransfersRoute,
  RuPaphosAirportTransfersRoute: RuPaphosAirportTransfersRoute,
  RuPricingRoute: RuPricingRoute,
  RuReviewsRoute: RuReviewsRoute,
  RuTaxiToChlorakaRoute: RuTaxiToChlorakaRoute,
  RuTaxiToCoralBayRoute: RuTaxiToCoralBayRoute,
  RuTaxiToLimassolRoute: RuTaxiToLimassolRoute,
  RuTaxiToPeyiaRoute: RuTaxiToPeyiaRoute,
  RuIndexRoute: RuIndexRoute,
}

const RuRouteWithChildren = RuRoute._addFileChildren(RuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CyprusAirportTransfersRoute: CyprusAirportTransfersRoute,
  ElRoute: ElRouteWithChildren,
  FaqRoute: FaqRoute,
  FleetRoute: FleetRoute,
  IndexDotphpRoute: IndexDotphpRoute,
  LarnacaAirportToAyiaNapaRoute: LarnacaAirportToAyiaNapaRoute,
  LarnacaAirportToPaphosRoute: LarnacaAirportToPaphosRoute,
  LarnacaAirportToProtarasRoute: LarnacaAirportToProtarasRoute,
  LarnacaAirportTransfersRoute: LarnacaAirportTransfersRoute,
  MercedesW213VipRoute: MercedesW213VipRoute,
  PaphosAirportTransfersRoute: PaphosAirportTransfersRoute,
  PricingRoute: PricingRoute,
  ReviewsRoute: ReviewsRoute,
  RuRoute: RuRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxiToChlorakaRoute: TaxiToChlorakaRoute,
  TaxiToCoralBayRoute: TaxiToCoralBayRoute,
  TaxiToLimassolRoute: TaxiToLimassolRoute,
  TaxiToPeyiaRoute: TaxiToPeyiaRoute,
  ZooInPaphosRoute: ZooInPaphosRoute,
  BlogBestBeachesPaphosCoralBayRoute: BlogBestBeachesPaphosCoralBayRoute,
  BlogCompleteCyprusAirportTransferGuideRoute:
    BlogCompleteCyprusAirportTransferGuideRoute,
  BlogCyprusTravelTipsFirstTimeVisitorsRoute:
    BlogCyprusTravelTipsFirstTimeVisitorsRoute,
  BlogHiddenGemsChlorakaKissonergaRoute: BlogHiddenGemsChlorakaKissonergaRoute,
  BlogLarnacaAirportToPaphosTravelGuideRoute:
    BlogLarnacaAirportToPaphosTravelGuideRoute,
  BlogThingsToDoInPaphosRoute: BlogThingsToDoInPaphosRoute,
  BlogTopHotelsVillasCoralBayPeyiaRoute: BlogTopHotelsVillasCoralBayPeyiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
